security:
    encoders:
         AppBundle\Entity\AuthUser:
             algorithm: bcrypt

    providers:
        auth_token_user_provider:
            id: auth_token_user_provider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            stateless: true
            simple_preauth:
                authenticator: app_services_auth_token_authenticator
            provider: auth_token_user_provider
            anonymous: ~